version: "3.3"

services:

  flask:
    build: ./flask_app
    container_name: flask_app
    restart: always
    volumes:
       - flask:/app
    depends_on:
      - "postgres"
    networks:
      - backend
      - frontend
    environment:
      - APP_NAME=FlaskTask
    expose:
      - 5000



  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    networks:
      - frontend
    ports:
      - "80:80"


  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dockerr}
      POSTGRES_DB:  ${POSTGRES_DB:-docker}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge


volumes:
    postgres:
    flask:
